name: Release

on:
  workflow_call:
    inputs:
      versionPrefix:
        required: false
        type: string
        description: "Optional prefix to add before version number"
        default: "v"

jobs:
  Semantic_Release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          submodules: true

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.2.0

      - run: npm ci

      - name: Import GPG key
        id: import-gpg
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.RELEASE_PRIVATE_PGP }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_config_global: true
          git_user_signingkey: true
          git_commit_gpgsign: true

      # Release
      - name: Semantic Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIT_AUTHOR_NAME: ${{ steps.import-gpg.outputs.name }}
          GIT_AUTHOR_EMAIL: ${{ steps.import-gpg.outputs.email }}
          GIT_COMMITTER_NAME: ${{ steps.import-gpg.outputs.name }}
          GIT_COMMITTER_EMAIL: ${{ steps.import-gpg.outputs.email }}
        run: |
          npx semantic-release

      - id: versionNumber
        run: echo "::set-output name=version::$SEMVER_VERSION"

      - name: Sign Tag
        env:
          SEMVER_VERSION: ${{ steps.versionNumber.outputs.version }}
        run: |
          if [ -z "$SEMVER_VERSION" ]
          then
            echo "No Release Version Set. Skip tagging"
          else
            echo "Version: ${{ inputs.versionPrefix }}${SEMVER_VERSION}"
            git tag "${{ inputs.versionPrefix }}${SEMVER_VERSION}" "${{ inputs.versionPrefix }}${SEMVER_VERSION}" -f -s -m "Sign Tag"
            export GIT_COMMITTER_DATE="$(git log -1 --format=%aD ${{ inputs.versionPrefix }}${SEMVER_VERSION})"
            git push origin "${{ inputs.versionPrefix }}${SEMVER_VERSION}" -f
          fi
